import Foundation
import CoreGraphics
import ImageIO
import UniformTypeIdentifiers
import XCTest

/// Test fixtures are **generated**, never checked in: LUTzy's inputs are RAWs
/// and LUT files that run to tens of MB, and a repo full of binary fixtures ages
/// badly. Everything here builds its input from scratch in a temp directory.
enum Fixtures {

    // MARK: - Scratch directory

    /// A unique temp directory that the caller is responsible for removing.
    static func makeTempDirectory(_ label: String = "LUTzyTests") throws -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(label)-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    // MARK: - .cube files

    /// Text of an identity cube of the given size, in the standard layout
    /// (R fastest, then G, then B).
    static func identityCubeText(size: Int, title: String = "identity") -> String {
        var lines = [
            "# generated by LUTzy tests",
            "TITLE \"\(title)\"",
            "LUT_3D_SIZE \(size)",
        ]
        let denom = Float(size - 1)
        for b in 0..<size {
            for g in 0..<size {
                for r in 0..<size {
                    lines.append(String(
                        format: "%.6f %.6f %.6f",
                        Float(r) / denom, Float(g) / denom, Float(b) / denom
                    ))
                }
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// Write `text` to `name` inside `directory`, optionally converting the line
    /// endings first (several vendor LUTs in the wild ship CRLF).
    @discardableResult
    static func writeCube(
        _ text: String,
        named name: String,
        in directory: URL,
        lineEnding: String = "\n"
    ) throws -> URL {
        let url = directory.appendingPathComponent(name)
        let converted = lineEnding == "\n"
            ? text
            : text.replacingOccurrences(of: "\n", with: lineEnding)
        try converted.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    // MARK: - Images

    /// A solid-color RGB CGImage.
    static func makeCGImage(width: Int, height: Int, red: CGFloat = 0.5,
                            green: CGFloat = 0.4, blue: CGFloat = 0.3) throws -> CGImage {
        let space = CGColorSpaceCreateDeviceRGB()
        guard let ctx = CGContext(
            data: nil, width: width, height: height,
            bitsPerComponent: 8, bytesPerRow: width * 4, space: space,
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        ) else { throw FixtureError.cannotCreateContext }
        ctx.setFillColor(red: red, green: green, blue: blue, alpha: 1)
        ctx.fill(CGRect(x: 0, y: 0, width: width, height: height))
        guard let image = ctx.makeImage() else { throw FixtureError.cannotCreateContext }
        return image
    }

    /// Write a JPEG whose **pixel buffer** is `width`×`height` but which carries
    /// `orientation` as its EXIF tag — i.e. exactly what a camera writes when
    /// the body was rotated. Orientation 6 means "rotate 90° CW to display", so
    /// a landscape buffer displays as portrait.
    @discardableResult
    static func writeJPEG(
        width: Int,
        height: Int,
        orientation: Int,
        named name: String,
        in directory: URL
    ) throws -> URL {
        let url = directory.appendingPathComponent(name)
        let image = try makeCGImage(width: width, height: height)
        guard let dest = CGImageDestinationCreateWithURL(
            url as CFURL, UTType.jpeg.identifier as CFString, 1, nil
        ) else { throw FixtureError.cannotCreateDestination }

        let properties: [CFString: Any] = [
            kCGImagePropertyOrientation: orientation,
            kCGImagePropertyTIFFDictionary: [
                kCGImagePropertyTIFFOrientation: orientation,
            ] as [CFString: Any],
        ]
        CGImageDestinationAddImage(dest, image, properties as CFDictionary)
        guard CGImageDestinationFinalize(dest) else { throw FixtureError.cannotWriteImage }
        return url
    }

    /// Write a JPEG carrying a set of EXIF/TIFF/GPS values, for metadata tests.
    @discardableResult
    static func writeJPEG(
        named name: String,
        in directory: URL,
        exif: [CFString: Any] = [:],
        tiff: [CFString: Any] = [:],
        gps: [CFString: Any] = [:]
    ) throws -> URL {
        let url = directory.appendingPathComponent(name)
        let image = try makeCGImage(width: 64, height: 48)
        guard let dest = CGImageDestinationCreateWithURL(
            url as CFURL, UTType.jpeg.identifier as CFString, 1, nil
        ) else { throw FixtureError.cannotCreateDestination }

        var properties: [CFString: Any] = [:]
        if !exif.isEmpty { properties[kCGImagePropertyExifDictionary] = exif }
        if !tiff.isEmpty { properties[kCGImagePropertyTIFFDictionary] = tiff }
        if !gps.isEmpty { properties[kCGImagePropertyGPSDictionary] = gps }
        CGImageDestinationAddImage(dest, image, properties as CFDictionary)
        guard CGImageDestinationFinalize(dest) else { throw FixtureError.cannotWriteImage }
        return url
    }

    /// Dimensions ImageIO reports for a file on disk.
    static func storedSize(of url: URL) -> CGSize? {
        guard let source = CGImageSourceCreateWithURL(url as CFURL, nil),
              let props = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let w = props[kCGImagePropertyPixelWidth] as? Int,
              let h = props[kCGImagePropertyPixelHeight] as? Int
        else { return nil }
        return CGSize(width: w, height: h)
    }

    enum FixtureError: Error {
        case cannotCreateContext
        case cannotCreateDestination
        case cannotWriteImage
    }
}

/// Base class that hands each test a scratch directory and cleans it up.
class TempDirectoryTestCase: XCTestCase {
    var tempDirectory: URL!

    override func setUpWithError() throws {
        try super.setUpWithError()
        tempDirectory = try Fixtures.makeTempDirectory(String(describing: type(of: self)))
    }

    override func tearDownWithError() throws {
        if let tempDirectory {
            try? FileManager.default.removeItem(at: tempDirectory)
        }
        tempDirectory = nil
        try super.tearDownWithError()
    }
}
