import Foundation
import CoreGraphics
import ImageIO
import UniformTypeIdentifiers
import XCTest
@testable import LumoKit

/// Test fixtures are **generated**, never checked in: Lumo's inputs are RAWs
/// and LUT files that run to tens of MB, and a repo full of binary fixtures ages
/// badly. Everything here builds its input from scratch in a temp directory.
enum Fixtures {

    // MARK: - Scratch directory

    /// A unique temp directory that the caller is responsible for removing.
    static func makeTempDirectory(_ label: String = "LumoTests") throws -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(label)-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    // MARK: - .cube files

    /// Text of an identity cube of the given size, in the standard layout
    /// (R fastest, then G, then B).
    static func identityCubeText(size: Int, title: String = "identity") -> String {
        var lines = [
            "# generated by Lumo tests",
            "TITLE \"\(title)\"",
            "LUT_3D_SIZE \(size)",
        ]
        let denom = Float(size - 1)
        for b in 0..<size {
            for g in 0..<size {
                for r in 0..<size {
                    lines.append(String(
                        format: "%.6f %.6f %.6f",
                        Float(r) / denom, Float(g) / denom, Float(b) / denom
                    ))
                }
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// Write `text` to `name` inside `directory`, optionally converting the line
    /// endings first (several vendor LUTs in the wild ship CRLF).
    @discardableResult
    static func writeCube(
        _ text: String,
        named name: String,
        in directory: URL,
        lineEnding: String = "\n"
    ) throws -> URL {
        let url = directory.appendingPathComponent(name)
        let converted = lineEnding == "\n"
            ? text
            : text.replacingOccurrences(of: "\n", with: lineEnding)
        try converted.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    // MARK: - Images

    /// A solid-color RGB CGImage.
    static func makeCGImage(width: Int, height: Int, red: CGFloat = 0.5,
                            green: CGFloat = 0.4, blue: CGFloat = 0.3) throws -> CGImage {
        let space = CGColorSpaceCreateDeviceRGB()
        guard let ctx = CGContext(
            data: nil, width: width, height: height,
            bitsPerComponent: 8, bytesPerRow: width * 4, space: space,
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        ) else { throw FixtureError.cannotCreateContext }
        ctx.setFillColor(red: red, green: green, blue: blue, alpha: 1)
        ctx.fill(CGRect(x: 0, y: 0, width: width, height: height))
        guard let image = ctx.makeImage() else { throw FixtureError.cannotCreateContext }
        return image
    }

    /// Write a JPEG whose **pixel buffer** is `width`×`height` but which carries
    /// `orientation` as its EXIF tag — i.e. exactly what a camera writes when
    /// the body was rotated. Orientation 6 means "rotate 90° CW to display", so
    /// a landscape buffer displays as portrait.
    @discardableResult
    static func writeJPEG(
        width: Int,
        height: Int,
        orientation: Int,
        named name: String,
        in directory: URL
    ) throws -> URL {
        let url = directory.appendingPathComponent(name)
        let image = try makeCGImage(width: width, height: height)
        guard let dest = CGImageDestinationCreateWithURL(
            url as CFURL, UTType.jpeg.identifier as CFString, 1, nil
        ) else { throw FixtureError.cannotCreateDestination }

        let properties: [CFString: Any] = [
            kCGImagePropertyOrientation: orientation,
            kCGImagePropertyTIFFDictionary: [
                kCGImagePropertyTIFFOrientation: orientation,
            ] as [CFString: Any],
        ]
        CGImageDestinationAddImage(dest, image, properties as CFDictionary)
        guard CGImageDestinationFinalize(dest) else { throw FixtureError.cannotWriteImage }
        return url
    }

    /// Write a JPEG carrying a set of EXIF/TIFF/GPS values, for metadata tests.
    @discardableResult
    static func writeJPEG(
        named name: String,
        in directory: URL,
        exif: [CFString: Any] = [:],
        tiff: [CFString: Any] = [:],
        gps: [CFString: Any] = [:]
    ) throws -> URL {
        let url = directory.appendingPathComponent(name)
        let image = try makeCGImage(width: 64, height: 48)
        guard let dest = CGImageDestinationCreateWithURL(
            url as CFURL, UTType.jpeg.identifier as CFString, 1, nil
        ) else { throw FixtureError.cannotCreateDestination }

        var properties: [CFString: Any] = [:]
        if !exif.isEmpty { properties[kCGImagePropertyExifDictionary] = exif }
        if !tiff.isEmpty { properties[kCGImagePropertyTIFFDictionary] = tiff }
        if !gps.isEmpty { properties[kCGImagePropertyGPSDictionary] = gps }
        CGImageDestinationAddImage(dest, image, properties as CFDictionary)
        guard CGImageDestinationFinalize(dest) else { throw FixtureError.cannotWriteImage }
        return url
    }

    /// A diagonal red→blue ramp as a `CGImage`.
    ///
    /// The solid-colour `makeCGImage` above is fine for geometry and orientation, but useless for the
    /// render pipeline: a flat patch survives a tone curve almost unchanged, so a test built on one
    /// would pass against a stage that never ran.
    static func makeGradientCGImage(width: Int, height: Int) throws -> CGImage {
        let space = CGColorSpace(name: CGColorSpace.sRGB)!
        guard let ctx = CGContext(
            data: nil, width: width, height: height,
            bitsPerComponent: 8, bytesPerRow: width * 4, space: space,
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        ) else { throw FixtureError.cannotCreateContext }

        guard let gradient = CGGradient(
            colorsSpace: space,
            colors: [
                CGColor(colorSpace: space, components: [0.9, 0.1, 0.1, 1])!,
                CGColor(colorSpace: space, components: [0.1, 0.2, 0.9, 1])!,
            ] as CFArray,
            locations: [0, 1]
        ) else { throw FixtureError.cannotCreateContext }

        ctx.drawLinearGradient(
            gradient,
            start: CGPoint(x: 0, y: 0),
            end: CGPoint(x: CGFloat(width), y: CGFloat(height)),
            options: [.drawsBeforeStartLocation, .drawsAfterEndLocation]
        )
        guard let image = ctx.makeImage() else { throw FixtureError.cannotCreateContext }
        return image
    }

    /// Write a gradient as **PNG** — lossless, so a test comparing a decode against a decode is
    /// measuring the pipeline rather than JPEG's ideas about chroma.
    @discardableResult
    static func writeGradientPNG(
        width: Int,
        height: Int,
        named name: String,
        in directory: URL
    ) throws -> URL {
        let url = directory.appendingPathComponent(name)
        let image = try makeGradientCGImage(width: width, height: height)
        guard let dest = CGImageDestinationCreateWithURL(
            url as CFURL, UTType.png.identifier as CFString, 1, nil
        ) else { throw FixtureError.cannotCreateDestination }
        CGImageDestinationAddImage(dest, image, nil)
        guard CGImageDestinationFinalize(dest) else { throw FixtureError.cannotWriteImage }
        return url
    }

    // MARK: - Local-only RAW

    /// A real RAW file, if this checkout happens to have one.
    ///
    /// Everything else here is generated, but a RAW cannot be: a synthetic DNG that `CIRAWFilter`
    /// will actually decode is a project of its own. Real-world fixtures are optional, so CI and
    /// checkouts without released camera files still skip RAW-dependent tests rather than fail.
    /// See `docs/PHASE2_SPEC.md` §8.9.
    static var localRAWURLs: [URL] {
        let repoRoot = URL(fileURLWithPath: #filePath)   // Tests/LumoKitTests/Fixtures.swift
            .deletingLastPathComponent()                 // Tests/LumoKitTests
            .deletingLastPathComponent()                 // Tests
            .deletingLastPathComponent()                 // repo root
        let folder = repoRoot.appendingPathComponent("realworldtest")
        guard let entries = try? FileManager.default.contentsOfDirectory(
            at: folder, includingPropertiesForKeys: nil
        ) else { return [] }
        return entries
            .filter { ImageDecoder.rawExtensions.contains($0.pathExtension.lowercased()) }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
    }

    static var localRAWURL: URL? {
        localRAWURLs.first
    }

    /// A real (RAW, in-camera JPG) pair, if this checkout happens to have one.
    ///
    /// The derive gate needs both halves of the same frame: the cube is fit by comparing a neutral
    /// RAW render against the JPEG the camera produced from it. Matched on the filename stem, because
    /// that is how cameras write the pair and how `realworldtest/` happens to hold one — anything
    /// looser could pick up an unrelated JPG and the geometry check would reject it with a confusing
    /// message.
    ///
    /// `nil` on CI, which never has a RAW. A test that needs this must `XCTSkip`.
    static var localRAWJPGPair: (raw: URL, jpg: URL)? {
        guard let raw = localRAWURL else { return nil }
        let stem = raw.deletingPathExtension().lastPathComponent
        let folder = raw.deletingLastPathComponent()
        guard let entries = try? FileManager.default.contentsOfDirectory(
            at: folder, includingPropertiesForKeys: nil
        ) else { return nil }
        guard let jpg = entries.first(where: {
            ["jpg", "jpeg"].contains($0.pathExtension.lowercased())
                && $0.deletingPathExtension().lastPathComponent == stem
        }) else { return nil }
        return (raw, jpg)
    }

    /// Dimensions ImageIO reports for a file on disk.
    static func storedSize(of url: URL) -> CGSize? {
        guard let source = CGImageSourceCreateWithURL(url as CFURL, nil),
              let props = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let w = props[kCGImagePropertyPixelWidth] as? Int,
              let h = props[kCGImagePropertyPixelHeight] as? Int
        else { return nil }
        return CGSize(width: w, height: h)
    }

    enum FixtureError: Error {
        case cannotCreateContext
        case cannotCreateDestination
        case cannotWriteImage
    }
}

/// Base class that hands each test a scratch directory and cleans it up.
class TempDirectoryTestCase: XCTestCase {
    var tempDirectory: URL!

    override func setUpWithError() throws {
        try super.setUpWithError()
        tempDirectory = try Fixtures.makeTempDirectory(String(describing: type(of: self)))
    }

    override func tearDownWithError() throws {
        if let tempDirectory {
            try? FileManager.default.removeItem(at: tempDirectory)
        }
        tempDirectory = nil
        try super.tearDownWithError()
    }
}
